#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
  ifeq ($(GNUSTEP_MAKEFILES),)
    $(warning )
    $(warning Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!)
    $(warning Perhaps gnustep-make is not properly installed,)
    $(warning so gnustep-config is not in your PATH.)
    $(warning )
    $(warning Your PATH is currently $(PATH))
    $(warning )
  endif
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = SFCompanion
APP_NAME = SFCompanion
SFCompanion_APPLICATION_ICON = 


#
# Libraries
#
SFCompanion_LIBRARIES_DEPEND_UPON += -lWebServices -lOresmeKit -lDataBasinKit 

#
# Resource files
#
SFCompanion_RESOURCE_FILES = \
Resources/SFCompanion.gorm \
Resources/AsyncTracker.gorm \
Resources/Log.gorm \
Resources/ProcessMonitor.gorm \
Resources/BatchTracker.gorm \
Resources/QueryCacher.gorm \
Resources/UserExecTracker.gorm \
Resources/Redeployer.gorm 


#
# Header files
#
SFCompanion_HEADER_FILES = \
AppController.h \
DBLogger.h \
AsyncTracker.h \
DBInteractiveTool.h \
ProcessMonitor.h \
BatchTracker.h \
QueryCacher.h \
UserExecTracker.h

#
# Objective-C Class files
#
SFCompanion_OBJC_FILES = \
AppController.m \
DBLogger.m \
AsyncTracker.m \
DBInteractiveTool.m \
ProcessMonitor.m \
BatchTracker.m \
QueryCacher.m \
UserExecTracker.m

#
# Other sources
#
SFCompanion_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
